version: '2'
services:
  jpa-layer:
    build: ./JpaLayer/
    depends_on:
      - database
    ports:
      - "8002:8002"
    environment:
      DATABASE: "database:5432"
      DATASOURCE_URL: "jdbc:postgresql://database:5432/transaction-broker"
      DB_USERNAME: "username"
      DB_PASSWORD: "password"
      KAFKA_BROKER: "kafka:9092"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INT://kafka:9092,LISTENER_EXT://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_EXT:PLAINTEXT,LISTENER_INT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "username"
      POSTGRES_DB: "transaction-broker"
      PGPASSWORD: "password"
      PGUSER: "username"
      PGDATABASE: "transaction-broker"
    volumes:
      - somename:/home/anton/FastDisk/programs/workspace/intellij/database
volumes:
  somename: